#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true


[[blocks.segments]]
type = "python"
style = "powerline"
powerline_symbol = ""
background = "transparent"
template = " {{ if .Error }}{{ .Error }}{{ else }}({{ .Major }}.{{ .Minor }}){{ end }} "


[[blocks.segments]]
type = 'path'
style = 'powerline'
powerline_symbol = ""
foreground = 'transparent'
background = 'blue'
template = ' {{ .Path }} '

[blocks.segments.properties]
style = 'full'


[[blocks.segments]]
type = 'git'
style = 'powerline'
powerline_symbol = ""
foreground = 'transparent'
foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}",
    "{{ if gt .Ahead 0 }}green{{ end }}",
    "{{ if gt .Behind 0 }}magenta{{ end }}",
    "lightBlue",
]
background = 'transparent'
template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}±{{ end }}{{ if .Staging.Changed }}✚{{ end }} "


[blocks.segments.properties]
commit_icon = '@'
fetch_status = true

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
type = "session"
style = "powerline"
powerline_symbol = ""
foreground = "lightBlue"
background = "transparent"

template = "{{ if .SSHSession }} {{ end }}{{ .UserName }}"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'


[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
template = '❯'

[transient_prompt]
foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
]
foreground = "white"
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
template = '❯❯ '
